### ISSUE TITLE
Spelling mistake 

### ISSUE THREAD

**Issue by jyotsanh** [lavshah19/portfolio-website-#1]
# Education Section
- Correct the spelling of "college."
- The name of the graduated college, "international," appears to be incorrect.

# Everything Looks Good

**Comment by lavshah19** [comment]
Thanks a lot for spotting the spelling error in my code—I totally missed it, and your sharp eyes made all the difference. It's amazing how a simple typo can cause unexpected issues, and your vigilance saved us from potential confusion down the road. I appreciate your meticulousness and the support you bring to our work. Thanks for keeping us on track, and I'll definitely double-check my spelling next time to avoid these slip-ups. It’s great to know we have a team that watches out for each other.

**Comment by jyotsanh** [comment]
Bro , No need to stretch it . It's my duty as your fellow github user to inform you with your "mistakes". Hope you resolved your **SPELLING** mistake
